repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-toml
        name: Check TOML files
        stages: [push]
      - id: check-yaml
        name: Check YAML files
        args: [--allow-multiple-documents]
        stages: [push]
      - id: end-of-file-fixer
        name: End files with single empty line
        stages: [push]
      - id: trailing-whitespace
        name: Remove trailing whitespace
        stages: [push]
      - id: detect-private-key
        name: Detect private keys
        stages: [push]

  - repo: local
    hooks:
      - id: isort
        name: Sort imports with isort
        entry: poetry run isort
        pass_filenames: true
        types: [python]
        language: system
        require_serial: false
        stages: [push]

      - id: black
        name: Format code with black
        entry: poetry run black
        pass_filenames: true
        types: [python]
        language: system
        require_serial: false
        stages: [push]

      - id: flake8
        name: Check style with flake8
        entry: poetry run flake8
        pass_filenames: true
        types: [python]
        language: system
        require_serial: false

      - id: mypy
        name: Typecheck with mypy
        entry: poetry run mypy .
        pass_filenames: false
        types: [python]
        language: system
        require_serial: false

      - id: pytest
        name: Run tests with pytest
        entry: poetry run pytest --random-order --cov-fail-under=50
        pass_filenames: false
        types: [python]
        language: system
        verbose: true
        require_serial: false

      - id: safety
        name: Check dependencies with safety
        entry: poetry run safety check
        pass_filenames: false
        types: [python]
        language: system
        stages: [push]
        require_serial: false

      - id: bandit
        name: Check security issues with bandit
        entry: poetry run bandit -r .
        pass_filenames: false
        types: [python]
        language: system
        stages: [push]
        require_serial: false
